### PR TITLE
Refactor the client and the demo

### PR DESCRIPTION
**Pull request by VMitov**
- deprecate mpad.js
- update to the latest github.com/coreos/go-oidc
- change the redirect-url handler to /login
- update jQuery
- add Dockerfile for the demo

### CODE REVIEW

**Comment by VMitov** [comment]
Because it is such a thin wrapper I'm struggling to think of a useful unit test.

**Comment by simeon-aladjem** [comment]
I embrace the simplification, but I do not like the following:
# We now made the 3rd party objects `oidc.Provider` and `oidc.IDTokenVerifier` part of our API, meaning that if we change the OIDC library with a different one, we cannot avoid changing our API too. This is not a positive thing. It would be better to abstract the 3rd party API with our own, so changes like this might be done preserving the API.
# I do not like the bare-bones demo app UI. It was much better with the slight upgrade of the bootstrap, and I think it was not interfering too much. Moreover, it was more or less alike the UI of the other SDK's demo apps.
Generally speaking, I do believe that similar API for the different SDK's adds a lot, at least in terms of documentation and understanding how the SDKs work. I have seen many SDK's from different big providers being documented in a generic way, and then having code snippets for the same functionality in several different languages. We cannot do that if the SDKs have totally different APIs.

**Comment by VMitov** [comment]
- For the API, I will think about it, but I don't wanna write and support any code just to abstract it. Even more, the Go community is more likely to be used to the oidc API and hence - it will be easier for it to use the SDK and not try to learn new one. And this will be true for each community. I don't want to reinvent the wheel. 
- The original UI was prettier, this one is easier to maintain. We can do some small improvements, but I strongly suggest we don't get back to any CSS framework.

**Comment by todinov** [comment]
Added some styling to the sample app. It is pretty close to how it used to look with a lot less bloat.

**Pull request merged**
